### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by eevleevs** [kodi-bino/plugin.video.mediasetplay#13]
I am getting this exception at plugin start on RPi with LibreELEC 9.0.2, Kodi 18.2

> 2019-10-28 17:59:37.737 T:1501557616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name where
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediasetplay/main.py", line 14, in <module>
                                                from resources.lib.mediaset import mediaset
                                              File "/storage/.kodi/addons/plugin.video.mediasetplay/resources/lib/mediaset.py", line 12, in <module>
                                                import requests
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 112, in <module>
                                                from . import utils
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/utils.py", line 24, in <module>
                                                from . import certs
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/certs.py", line 15, in <module>
                                                from certifi import where
                                            ImportError: cannot import name where
                                            -->End of Python script error report<--
2019-10-28 17:59:37.758 T:1789887344   ERROR: GetDirectory - Error getting plugin://plugin.video.mediasetplay/
2019-10-28 17:59:37.760 T:1936695312   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediasetplay/) failed

**Comment by kodi-bino** [comment]
Try updating Libreelec to latest version available 9.2.0.
I'm using it on the new version and is working perfectly.

If not I need a more detailed log, a full log from boot to error will be perfect.
Thanks.

**Comment by eevleevs** [comment]
Looks like a problem with requests 2.20. Works again by downgrading to 2.14.
