### ISSUE TITLE
Non funziona piu' vedere errore sotto - grazie

### ISSUE THREAD

**Issue by Condottiero1** [kodi-bino/plugin.video.mediasetplay#14]
2019-11-05 08:36:55.131 T:19468   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named html.entities
                                            Traceback (most recent call last):
                                              File "C:\Users\Bijan\Kodi portable\Kodi\portable_data\addons\plugin.video.mediasetplay\main.py", line 14, in <module>
                                                from resources.lib.mediaset import mediaset
                                              File "C:\Users\Bijan\Kodi portable\Kodi\portable_data\addons\plugin.video.mediasetplay\resources\lib\mediaset.py", line 16, in <module>
                                                from bs4 import BeautifulSoup
                                              File "C:\Users\Bijan\Kodi portable\Kodi\portable_data\addons\script.module.beautifulsoup4\lib\bs4\__init__.py", line 36, in <module>
                                                from .builder import builder_registry, ParserRejectedMarkup
                                              File "C:\Users\Bijan\Kodi portable\Kodi\portable_data\addons\script.module.beautifulsoup4\lib\bs4\builder\__init__.py", line 7, in <module>
                                                from bs4.element import (
                                              File "C:\Users\Bijan\Kodi portable\Kodi\portable_data\addons\script.module.beautifulsoup4\lib\bs4\element.py", line 13, in <module>
                                                from bs4.dammit import EntitySubstitution
                                              File "C:\Users\Bijan\Kodi portable\Kodi\portable_data\addons\script.module.beautifulsoup4\lib\bs4\dammit.py", line 14, in <module>
                                                from html.entities import codepoint2name
                                            ImportError: No module named html.entities
                                            -->End of Python script error report<--
2019-11-05 08:36:55.155 T:14076   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mediasetplay/
2019-11-05 08:36:55.176 T:14256   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediasetplay/) failed

**Comment by kodi-bino** [comment]
Ciao, testato ora con Kodi 18.5 su Windows 10 e funziona perfettamente.
Se il problema persiste avrei bisogno di qualche altra informazione e magari di un log completo dal boot fino al presentarsi dell'errore.
Su quale sistema operativo sei? Con quale versione di Kodi?
