### ISSUE TITLE
Non funziona neanche version 1.2.1 - vedere errore sotto - grazie

### ISSUE THREAD

**Issue by Condottiero1** [kodi-bino/plugin.video.mediasetplay#15]
2019-11-07 09:03:41.125 T:11788   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Bijan\Documents\Kodi_Leia2\Kodi\portable_data\addons\plugin.video.mediasetplay\main.py", line 131, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Bijan\Documents\Kodi_Leia2\Kodi\portable_data\addons\plugin.video.mediasetplay\main.py", line 57, in router
                                                mediaset.getOnDemandProgramDetailsCategory(_handle, _url, params['brandId'], params['subBrandId'])
                                              File "C:\Users\Bijan\Documents\Kodi_Leia2\Kodi\portable_data\addons\plugin.video.mediasetplay\resources\lib\mediaset.py", line 243, in getOnDemandProgramDetailsCategory
                                                if thumbs[0]:
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-11-07 09:03:41.181 T:2204   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.mediasetplay/?action=list&brandId=100001392&subBrandId=100002006&type=ondemand
2019-11-07 09:03:41.184 T:14584   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediasetplay/?action=list&brandId=100001392&subBrandId=100002006&type=ondemand) failed
2019-11-07 09:03:41.738 T:10284  NOTICE: action=list&brandId=100001392&category=Programmi%20Tv&type=ondemand

**Comment by kodi-bino** [comment]
Duplicato, vedere #14
